// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SlideoverController from "./slideover_controller"
application.register("slideover", SlideoverController)
